#pragma once
#include "Vec3.hpp"
#include <vector>
#include <cstdint>
#include <string>

namespace sim {

class Room;

// ─── SquadStatus ─────────────────────────────────────────────────────────────
enum class SquadStatus { Normal, Confused, Broken };

// ─── SquadOrderType ──────────────────────────────────────────────────────────
enum class SquadOrderType { Hold, Attack, Retreat };

// ─── NpcCommand ──────────────────────────────────────────────────────────────
// The ONLY way to drive NPC behavior when the NPC belongs to a Squad.
// Squad is the sole issuer of NpcCommands — NPCs never self-command.

enum class NpcCommandType {
    EngageTarget,   // Chase + attack the given target
    HoldSlot,       // Hold position; react to immediate (attackRange) threats only
    Retreat,        // Move to destination, then Idle
    Confused,       // Disorient for CONFUSION_DURATION (issued on leader death)
    Idle,           // Default: do nothing
};

struct NpcCommand {
    NpcCommandType type           { NpcCommandType::Idle };
    uint32_t       targetId       { 0 };    // EngageTarget: target actor id
    Vec3           destination    {};       // Retreat: destination position
    float          speedMultiplier{ 1.f };  // 1.0=normal, 0.5=slow
};

// ─── NpcReport ───────────────────────────────────────────────────────────────
// Generated by Npc::buildReport(), consumed by Squad.
// Uses int state (not NpcState) to avoid circular include with Npc.hpp.

struct NpcReport {
    uint32_t npcId         { 0 };
    int      state         { 0 };   // NpcState as int
    Vec3     position      {};
    uint32_t currentTarget { 0 };   // 0 = not targeting
    float    hpRatio       { 1.f }; // hp / maxHp
    bool     alive         { true };
    bool     isLeader      { false };
};

// ─── SquadReport ─────────────────────────────────────────────────────────────
// Generated by Squad::buildReport(), consumed by Platoon.

struct SquadReport {
    int         squadId          { -1 };
    int         aliveCount       { 0 };
    int         totalCount       { 0 };
    float       avgHpRatio       { 0.f };
    SquadStatus status           { SquadStatus::Normal };
    Vec3        center           {};
    uint32_t    engagedTarget    { 0 };
    bool        inCombat         { false };
    bool        leaderAlive      { false };
    float       combatEfficiency { 1.f }; // aliveCount/totalCount × avgHpRatio
};

// ─── Squad ───────────────────────────────────────────────────────────────────
// Mid-tier coordinator: owns NpcCommand dispatch, target selection,
// and leader-death cascade. Never modifies NPC FSM internals directly.

class Squad {
public:
    explicit Squad(int squadId);

    // Called by Room::updateSquads(), BEFORE NPC updates each tick.
    void update(float dt, Room& room);

    // Platoon → Squad: set order before this tick's update.
    // Broken state silently ignores tactical orders (Attack/Hold).
    void setPlatoonOrder(SquadOrderType type,
                         uint32_t        targetOverride = 0,
                         Vec3            destination    = {});

    // Squad → Platoon: snapshot of current state (call after update each tick).
    SquadReport buildReport(Room& room) const;

    // ── Accessors ────────────────────────────────────────────────────────────
    int            getSquadId()        const { return squadId_; }
    uint32_t       getLeaderId()       const { return leaderNpcId_; }
    uint32_t       getTargetPlayerId() const { return targetPlayerId_; }
    SquadStatus    getStatus()         const { return status_; }
    SquadOrderType getOrder()          const { return order_; }
    bool           isEmpty()           const { return members_.empty(); }

    const std::vector<uint32_t>& getMembers() const { return members_; }

    // ── Mutators (called during squad setup) ─────────────────────────────────
    void addMember(uint32_t npcId, bool asLeader = false);
    void setOrder(SquadOrderType order) { order_ = order; }

private:
    // ── update sub-steps (fixed call order) ──────────────────────────────────
    void removeDeadMembers  (Room& room);
    void checkLeaderValidity(Room& room);        // death → enter Confused
    void updateConfused     (float dt, Room& room);
    void updateBroken       (float dt, Room& room);
    void disband            (Room& room);
    void selectTarget       (float dt, Room& room);
    void pushCommandsToMembers(Room& room);

    // ── Data ─────────────────────────────────────────────────────────────────
    int                    squadId_;
    uint32_t               leaderNpcId_{ 0 };
    uint32_t               targetPlayerId_{ 0 };
    std::vector<uint32_t>  members_;
    SquadOrderType         order_{ SquadOrderType::Attack };
    SquadStatus            status_{ SquadStatus::Normal };
    float                  confusionTimer_{ 0.f };
    float                  targetMemoryTimer_{ 0.f };

    // Pending Platoon directive (set via setPlatoonOrder, consumed in update)
    SquadOrderType         platoonOrderType_{ SquadOrderType::Hold };
    uint32_t               platoonTargetOverride_{ 0 };  // 0 = squad picks own
    Vec3                   platoonDestination_{};
    bool                   hasPlatoonOrder_{ false };

    static constexpr float CONFUSION_DURATION    = 3.0f;
    static constexpr float TARGET_MEMORY_DURATION = 4.0f;
    static constexpr int   MIN_MEMBERS_TO_DISBAND  = 2;
};

} // namespace sim
